---
jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: yml2env
    trigger: true
  - set_pipeline: yml2env
    file: yml2env/ci/pipeline.yml

- name: test
  public: true
  plan:
  - get: cfops-image
  - get: yml2env
    trigger: true
    passed: [set-pipeline]
  - task: test
    file: yml2env/ci/tasks/test/task.yml

- name: release
  public: true
  plan:
  - get: yml2env
    trigger: false
    passed: [test]
  - get: cfops-image
  - task: build
    image: cfops-image
    passed: [test]
    file: yml2env/ci/tasks/release/task.yml
  - put: yml2env-release
    params:
      name: yml2env/version
      tag: yml2env/version
      tag_prefix: v
      globs: [build/yml2env*]

- name: test-prs
  plan:
  - get: cfops-image
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: test
    image: cfops-image
    config:
      platform: linux
      inputs:
      - name: pull-request
        path: gopath/src/github.com/EngineerBetter/yml2env
      run:
        path: gopath/src/github.com/EngineerBetter/yml2env/ci/tasks/test/run.sh
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure
  - put: pull-request
    params:
      path: pull-request
      status: success

resources:
- name: yml2env
  type: git
  source:
    uri: https://github.com/EngineerBetter/yml2env.git
    branch: master
- name: pull-request
  type: pull-request
  source:
    access_token: ((github_access_token))
    repo: EngineerBetter/yml2env
- name: yml2env-release
  type: github-release
  source:
    user: EngineerBetter
    repository: yml2env
    access_token: ((github_access_token))
- name: cfops-image
  type: docker-image
  icon: docker
  source:
    repository: engineerbetter/cf-ops
    username: ((dockerhub_user))
    password: ((dockerhub_password))

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr