---
jobs:
- name: test
  public: true
  plan:
  - get: yml2env
    trigger: true
  - task: test
    file: yml2env/ci/tasks/test/task.yml

- name: release
  public: true
  plan:
  - get: yml2env
    trigger: false
    passed: [test]
  - task: build
    file: yml2env/ci/tasks/release/task.yml
  - put: yml2env-release
    params:
      name: yml2env/version
      tag: yml2env/version
      tag_prefix: v
      globs: [build/yml2env*]

- name: test-prs
  plan:
  - get: pull-request
    trigger: true
    version: every
  - put: pull-request
    params:
      path: pull-request
      status: pending
  - task: test
    file: pull-request/ci/tasks/test/task.yml
    input_mapping: {yml2env: pull-request}
    on_failure:
      put: pull-request
      params:
        path: pull-request
        status: failure
  - put: pull-request
    params:
      path: pull-request
      status: success

resources:
- name: yml2env
  type: git
  source:
    uri: https://github.com/EngineerBetter/yml2env.git
    branch: master
- name: pull-request
  type: pull-request
  source:
    access_token: {{github-access-token}}
    repo: EngineerBetter/yml2env
- name: yml2env-release
  type: github-release
  source:
    user: EngineerBetter
    repository: yml2env
    access_token: {{github-access-token}}

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
